### ISSUE TITLE
REST Error:404 Message: https://developers.google.com/accounts/docs/AuthForInstalledApps

### ISSUE THREAD

**Issue by hubertbanas** [davesteele/cloudprint-service#24] opened 2015-05-28 01:24 UTC
It just stopped working today (2015/05/27). Here is the error message:

```code
sudo service cloudprintd start

Traceback (most recent call last):
  File "/usr/sbin/cloudprintd", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 510, in main
    sync_printers(cups_connection, cpp)
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 334, in sync_printers
    remote_printers = dict([(p.name, p) for p in cpp.get_printers()])
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 181, in get_printers
    r = self.get_rest()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 177, in get_rest
    auth = self.get_auth()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 103, in get_auth
    'application/x-www-form-urlencoded')
  File "/usr/share/cloudprint/cloudprint/rest.py", line 122, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/share/cloudprint/cloudprint/rest.py", line 105, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
cloudprint.rest.RESTException: REST Error:404
Message: https://developers.google.com/accounts/docs/AuthForInstalledApps
```
I'm able to login to the google account with no problems. All of my printers are there but for some unknown reason cloudprint just stopped working. I'm seeing the same problem on two different Debian Wheezy systems located in two different physical locations. Both were working fine for a very long time. No configuration changes on my end.

According to the link:

>Important: ClientLogin has been officially deprecated since April 20, 2012 and is now no longer available. Requests to ClientLogin will fail with a HTTP 404 response. We encourage you to migrate to OAuth 2.0 as soon as possible.

**Comment by akabaka74** [comment] 2015-05-28 11:39
confirmed, same for me

**Comment by motorkap** [comment] 2015-05-28 13:00
Me too, looks like Google broke this software. Are there any plans to 'migrate to OAuth 2.0'?

**Comment by davesteele** [comment] 2015-05-28 15:08
*Are there any plans to 'migrate to OAuth 2.0'?*

Yes. I have an OAuth2 solution, and will migrate it to cloudprint-service. 

Google announced this change, and we are passed the deadline they set.

**Comment by motorkap** [comment] 2015-05-28 17:53
Thanks Dave, a fix would be much appreciated.

**Comment by tylla** [comment] 2015-05-29 13:04
A fix would be awesome.
Can we help with anything? Testing etc.?

**Comment by bmccarthy** [comment] 2015-05-30 04:46
Thanks for this software. I would like to use this software for an event this upcoming week.  Any chance the fix will be put in in the next couple days? I can help with testing if you need it.

**Comment by davesteele** [comment] 2015-05-31 15:02
*Can we help with anything? Testing etc.?*

Test 0.11-7 on the [website](http://davesteele.github.io/cloudprint-service/).

It's been put together quickly, and I found I had to implement systemd support to get it to work. Check out the new man pages.

You can fall back to just cloudprint if there are problems with the service.

**Comment by motorkap** [comment] 2015-05-31 19:36
Hi Dave,
I'm struggling a bit to work out what I need to do. This is what I did so far on my headless raspberry pi:
(apt-get update)
Preparing to replace cloudprint-service 0.11-5.1 (using .../cloudprint-service_0.11-7_all.deb) ...
Unpacking replacement cloudprint-service ...
Processing triggers for man-db ...
locale: Cannot set LC_ALL to default locale: No such file or directory
Setting up cloudprint-service (0.11-7) ...
pi@SqueezePi ~ $ service cloudprintd status
[FAIL] cloudprint is not running ... failed!                       (as expected)
pi@SqueezePi ~ $ service cloudprintd start
No authentication found - run 'service cloudprintd login' as root

(running this gives the same error as before, so I went back and ready your post again and decided I need to RTFM)

pi@SqueezePi ~ $ man cloudprint-service

(from this I learn that I probably need to set some credentials up using cps-auth, but that doesn't work as it tries to start a browser in the UI. However, my Pi is headless so that doesn't work. Then I discover that you have even thought of that and I need to run cloudprint-auth. Tried that, command not found. Had a look for /var/lib/cloudprint/authfile, but no cloudprint directory (only /var/lib/cloudprintd. Decided to install cloudprint). 

pi@SqueezePi ~ $ sudo pip install cloudprint
Downloading/unpacking cloudprint
  Running setup.py egg_info for package cloudprint
    
Installing collected packages: cloudprint
  Running setup.py install for cloudprint
    
    Installing cloudprint script to /usr/local/bin
Successfully installed cloudprint
Cleaning up...

Still no cloudprint-auth command. What now, where did I go wrong?

**Comment by davesteele** [comment] 2015-05-31 20:04
My OAuth2 implementation needs a graphical browser environment to get the credentials. Here's what to do:

From a computer with a desktop, run cloudprint -c to establish credentials. Copy the resulting ~/.cloudprint.auth to the actual server. (if the login doesn't prompt you, delete the file to  'logout'). The destination file is /var/lib/cloudprint/authfile.

Cloudprint-service requires systemd now. If that is too much of a headache, you can run cloudprint bare (e.g. cloudprint -d) till things settle down.

**Comment by bmccarthy** [comment] 2015-06-01 01:10
I get the below error message when attempting to install on a new raspberry pi 2 B. Not sure if it is related to any changes made.

pi@raspberrypi ~ $ sudo apt-get install cloudprint cloudprint-service
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cloudprint : Depends: python:any (>= 2.7) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by redstar3894** [comment] 2015-06-01 01:14
@bmccarthy You need to upgrade to Raspbian Jessie in order to install the update currently, raspbian wheezy doesn't have the correct python version.

@davesteele I was able to install the packages using a raspberry pi, but cloudprint-auth fails when using X forwarded over SSH and still doesn't recognize a graphical environment

pi@archangel ~ $ cps-auth ************
non-network local connections being added to access control list
Graphical environment needed for OAuth2 login
pi@archangel ~ $ cloudprint-auth *************
Traceback (most recent call last):
  File "/usr/bin/cloudprint-auth", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-auth')()
  File "/usr/share/cloudprint/cloudprint/cpoauth.py", line 166, in main
    access, refresh = oauth.generate_tokens(login)
  File "/usr/share/cloudprint/cloudprint/cpoauth.py", line 137, in generate_tokens
    code = self.get_code(login)
  File "/usr/share/cloudprint/cloudprint/cpoauth.py", line 56, in get_code
    GLib.threads_init()
NameError: global name 'GLib' is not defined

I've been looking around, and it doesn't look like there's a python-glib package I'm missing, but I'm not sure what else might be happening?

**Comment by akabaka74** [comment] 2015-06-01 07:49
hi, 
i also having som issues installing:
when trying 
apt-get install cloudprint-service
i get:
 cloudprint-service : Depends: init-system-helpers (>= 1.18~) but it is not installable
and i'm not able to manage to install it,
so i tried cloudprint, but when i try something (like cloudprint -c or whatever else), i get:
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 38, in <module>
    import cpoauth
  File "/usr/share/cloudprint/cloudprint/cpoauth.py", line 16, in <module>
    from gi.repository import Gtk
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 76, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 224, in _load
    overrides_modules = __import__('gi.overrides', fromlist=[self._namespace])
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1533, in <module>
    raise RuntimeError("Gtk couldn't be initialized")
RuntimeError: Gtk couldn't be initialized
 i'm not sure what the problem is in here
any help will be appreciated

**Comment by tylla** [comment] 2015-06-01 09:07
@bmccarthy @akabaka74 I was able to install the previous version (0.11-6) on a squeeze (6.0) Debian system by extracting the package, editing the control file to lower the required Python version and repacking the package.
And it worked... at least to the point of giving me the error mentioned in the issue title.
But I'm afraid this time it won't work as squeeze is really far from systemd.

@davesteele Thank you for the prompt answer.
Is your code (the simple cloudprint, not the service part) using anything specific to Python 2.7? Because if not, then the requirements could be lowered to Python 2.6 so those few of us with older Debian systems could use the package without any extra work.

**Comment by davesteele** [comment] 2015-06-01 16:56
@akabaka74, if this is on a server without a graphical environment, it looks like it fails differently than I expected. For a workaround, you can edit cpoauth.py to guarantee that one of the 'gi' imports fails with an ImportError ( or add RuntimeError to the exception list, the better choice).

@tylla, I don't support installation on Python 2.6 because I don't test it. I'd accept patches for that.

**Comment by motorkap** [comment] 2015-06-01 19:30
Dave, re "Cloudprint-service requires systemd now. If that is too much of a headache, you can run cloudprint bare (e.g. cloudprint -d) till things settle down."

When I installed systemd the cloudprint-service got uninstalled. If I then try to re-install cloudprint-service, the system removes systemd (see below). If I try to install cloudprint it fails needing python >= 2.7, but my python version is 2.7.1

I'd like to help with this but I don't have a lot of linux knowledge, and I just got stuck again.
___________
pi@SqueezePi ~ $ sudo apt-get install cloudprint-service
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libcryptsetup4 libsystemd-id128-0 libsystemd-journal0
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  init-system-helpers
The following packages will be REMOVED:
  libpam-systemd **systemd**
The following NEW packages will be installed:
  cloudprint-service init-system-helpers
0 upgraded, 2 newly installed, 2 to remove and 1 not upgraded.
Need to get 0 B/23.1 kB of archives.
After this operation, 3379 kB disk space will be freed.
Do you want to continue [Y/n]? n
Abort.
pi@SqueezePi ~ $ python --version
Python 2.7.3
pi@SqueezePi ~ $ sudo apt-get install cloudprint
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cloudprint : Depends: python:any (>= 2.7) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by davesteele** [comment] 2015-06-01 19:34
@motorkap, I forgot to remove a dependency on the (removed) sysv init system. I'll ship a fix shortly.

**Comment by tylla** [comment] 2015-06-02 08:38
@davesteele I'm not sure whether this is a separate issue, so for first I'm writing it here.
I managed to install the cloudprint package to a newly installed Debian Jessie and when I try to start it I get two similar error messages:
```
root@cloudprint:~# cloudprint -a /root/.cloudprintauth -vvv
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Setting DEBUG-level logging
Skipping Kyocera_FS-6525MFP
Skipping kyocera-tanari-gimi
Skipping Kyocera_TASKalfa_2551ci
^CTraceback (most recent call last):
......
```
The starting traceback is for the CTRL-C I hit after a few seconds.

Am I missing something? Any thoughts, suggestions?

**Comment by akabaka74** [comment] 2015-06-02 08:41
ok, thanks to yo, i finally manage to run cloudprint, by replacing except ImportError with except RuntimeError and by getting credential on a desktop computer.(be carfull, when starting it print all the jobs launched since the faillure).
i've try to make the cloudprint service working,
actually, when i try to install cloudprint-service, i still get get

cloudprint-service : Depends: init-system-helpers (>= 1.18~) but it is not installable,
i manage to install with tylia repacking trick, but as i am on ubuntu precise, i don't have systemd
so it didn't work. 
i'm not sure i'll go any further on this, if so, i'll inform you.
anyway thxs a lot for the help
cheers

**Comment by tylla** [comment] 2015-06-02 13:27
@akabaka74 watch out, your installed init-system-helper 1.7 is older than the required 1.18 so that's why you still get apt-get errors. (7 < 18 ;-)
The repack trick worked until cloudprint-service didn't depended on systemd, now it's useless.

**Comment by akabaka74** [comment] 2015-06-02 13:43
Of course, noon error,thks

**Comment by davesteele** [comment] 2015-06-02 14:02
I have some dependency errors that are causing install problems - I'll fix those shortly.

The latest cloudprint-service won't be useful to you unless you have systemd (which is in Debian stable). If you are adventurous, you can get and install just the old [init script](https://raw.githubusercontent.com/davesteele/cloudprint-service/cedf6937004bbf3526eb19f91ee71a9ca654debd/debian/cloudprint-service.cloudprintd.init) to /etc/init.d/cloudprintd. 

- note that there are two '-u' options in that script that need to be removed.
- run 'chkconfig cloudprintd on' to set up the script.

**Comment by davesteele** [comment] 2015-06-02 14:08
@tylla, for python 2.6, see armooo/cloudprint#97

**Comment by hubertbanas** [comment] 2015-06-02 14:11
Are there any plans to officially support init.d sometime in the future or it is systemd only from now on? I believe there are a lot of older still supported installs that would beneficial from init.d.

**Comment by davesteele** [comment] 2015-06-02 14:17
I only did the system conversion because my init.d environment appeared to be broken. 

I have no need to go back to sysv init, but would be happy to accept patches for dual environment support.

**Comment by akabaka74** [comment] 2015-06-02 14:23
i've used this to make the normal cloudprint work with init.d
inside /etc/init.d/cloudprint, paste:

#!/bin/bash
# /etc/rc.d/cloudprint
# Description: Starts the Google Cloud Print script on startup
# ----------------
#
### BEGIN INIT INFO
# Provides: Cloud-Print
# Required-Start: $cups $network $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start Google Cloud Print
### END INIT INFO

USER="root"
PIDFILE="/var/run/cloudprint/pid"

case $1 in
        start)
                echo -n "Starting Google Cloud Print: "
                sudo -u $USER cloudprint -d -p $PIDFILE
        ;;
        stop)
                echo -n "Stopping Google Cloud Print: "
                killall cloudprint
        ;;
        restart)
                echo -n "Restarting Google Cloud Print: "
                killall cloudprint
                sudo -u $USER cloudprint -d -p $PIDFILE
        ;;
        *)
                echo "Usage: cloudprint {start|stop|restart}"
        ;;
esac

and then run 
update-rc.d cloudprint defaults
to add it to yours rcX.d (start with the server)
with so you can run the /etv/init.d/cloudprint start||stop||restart
or service cloudprint start||stop||restart

**Comment by tylla** [comment] 2015-06-03 08:19
@davesteele Thank you for pointing out the python 2.6 solution. I will give it a try soon.

Do you have some suggestion about my issue with the **"Unable to init server: Could not connect: Connection refused"** error?

**Comment by mfraser** [comment] 2015-06-03 11:02
Tried running cloudprint -c from my desktop, but it is failing with:
Graphical environment needed for OAuth2 login

**Comment by davesteele** [comment] 2015-06-03 11:39
@tylla, I suspect you don't have the authentication set up.

@mfraser, the login code is looking for a GNOME environment, and the python-gi package.

**Comment by mfraser** [comment] 2015-06-03 12:01
On 3 Jun 2015 12:39, "davesteele" <notifications@github.com> wrote:
>
> @tylla, I suspect you don't have the authentication set up.
>
> @mfraser, the login code is looking for a GNOME environment, and the
python-gi package.

That would explain it, I'm using a KDE desktop.

**Comment by mfraser** [comment] 2015-06-03 12:05
On 3 Jun 2015 12:39, "davesteele" <notifications@github.com> wrote:
>
> @tylla, I suspect you don't have the authentication set up.
>
> @mfraser, the login code is looking for a GNOME environment, and the
python-gi package.

python-gi package is installed.

**Comment by tylla** [comment] 2015-06-03 13:07
@davesteele Nope, authentication is OK, I suspected that in some ways ssh's X11-forwarding was the cause. At least when I tried with the -Y flag to enable trusted forwarding, it changed the error message to some dbus activation message. Ahh, never mind.
I found out the real cause of my problem was that when I set up my new test machine, (in an bitter attempt to invisibly replace the printers behind the back of Google) I only copied the printer definition for CUPS but I forgot the .ppd files, so your code just skipped those printers as it should.
Just a suggestion: the **"Skipping " + printer_name** (cloudprint.py:314) string maybe should be changed to something like:
 to **"Parsing the PPD file of '" + printer_name + "' failed, skipping."**
Now that I studied your code, now it's clear what means "Skipped", but for first I couldn't really find out the cause. :)

So worksforme!

**Comment by dmonty2** [comment] 2015-06-03 15:21
@davesteele - would you be able to drop the GTK Gnome/GUI requirement?  One of the reasons why we went to cloudprint/service is so that we could drop the requirement for installing a running a full blown desktop environment with Google Chrome.  Plus we like the INCLUDE/EXCLUDE feature.

**Comment by davesteele** [comment] 2015-06-03 15:55
@dmonty2 - [Upstream](https://github.com/armooo/cloudprint/issues/97) removes the desktop requirement by printing a URL that must be visited elsewhere. My solution also has a remote auth script. Bottom line, you need a graphical environment somewhere for OAuth2

INCLUDE/EXCLUDE will be back.

**Closed** 2015-06-30 15:35 UTC

**Comment by vivek2007** [comment] 2015-08-19 02:42
Hi @davesteele 

Hi all, i am facing with OAuth version can you please help me

request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in get_token' /home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:inclientlogin'
/home/vivek/Documents/GTFS1/inc/ft.rb:10:in init' /home/vivek/Documents/GTFS1/inc/ft.rb:99:ingetTable'
/home/vivek/Documents/GTFS1/inc/ft.rb:28:in update' /home/vivek/Documents/GTFS1/Rakefile:435:inblock (3 levels) in '
/home/vivek/Documents/GTFS1/Rakefile:434:in each' /home/vivek/Documents/GTFS1/Rakefile:434:inblock (2 levels) in '
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in eval' /home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in

'
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)
vivek@vivek:~/Documents/GTFS1$ rake project:deploy_fusiontables
07:41:35 +0 : START Fusion Tables INSERTs
rake aborted!
request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in get_token' /home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:inclientlogin'
/home/vivek/Documents/GTFS1/inc/ft.rb:10:in init' /home/vivek/Documents/GTFS1/inc/ft.rb:99:ingetTable'
/home/vivek/Documents/GTFS1/inc/ft.rb:28:in update' /home/vivek/Documents/GTFS1/Rakefile:435:inblock (3 levels) in '
/home/vivek/Documents/GTFS1/Rakefile:434:in each' /home/vivek/Documents/GTFS1/Rakefile:434:inblock (2 levels) in '
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in eval' /home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in'
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)

**Comment by davesteele** [comment] 2016-02-15 22:14
See #36 for resolution.
